services:

  api-docker:
    container_name: api-docker
    build: .
    volumes:
      - ./backend:/var/www/html
    ports:
      - 9000:80
  
  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=phpmyadmin
        - MYSQL_USER=nicolas
        - MYSQL_PASSWORD=150a
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1